# Generated by Django 5.2.7 on 2025-12-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='申請日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='休み希望')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='ステータス')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mst_employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'シフト申請',
                'verbose_name_plural': 'シフト申請',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], verbose_name='曜日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='休み希望')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mst_employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '基本スケジュール',
                'verbose_name_plural': '基本スケジュール',
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
