# Generated by Django 5.2.7 on 2025-12-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mst_shop',
            fields=[
                ('shop_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Shop_ID')),
                ('shop_name', models.CharField(max_length=10, verbose_name='Shop_Name')),
                ('shop_addres', models.CharField(max_length=100, verbose_name='Shop_Address')),
                ('shop_tel', models.CharField(max_length=11, verbose_name='Shop_Tel')),
            ],
        ),
        migrations.CreateModel(
            name='mst_employee',
            fields=[
                ('employee', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Employee')),
                ('emp_name', models.CharField(max_length=30, verbose_name='Emp_Name')),
                ('emp_age', models.IntegerField(verbose_name='Emp_Age')),
                ('emp_email', models.CharField(max_length=50, verbose_name='Emp_Email')),
                ('emp_status', models.CharField(max_length=1, verbose_name='Emp_Status')),
                ('hire_date', models.DateField(verbose_name='Hire_Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('affiliated_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mst_shop')),
            ],
        ),
    ]
