# Generated by Django 5.2.7 on 2025-12-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_employee',
            name='emp_email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Emp_Email'),
        ),
    ]
