# Generated by Django 5.2.7 on 2025-12-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trn_clocking',
            fields=[
                ('clocking_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Clocking ID')),
                ('clocking_type', models.CharField(max_length=1, verbose_name='Clocking Type')),
                ('clocking_datetime', models.DateTimeField(verbose_name='Clocking DateTime')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mst_employee')),
            ],
        ),
        migrations.CreateModel(
            name='shift_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='Schedule Date')),
                ('start_time', models.TimeField(verbose_name='Start_Time')),
                ('end_time', models.TimeField(verbose_name='End_Time')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='common.mst_employee', verbose_name='従業員')),
            ],
            options={
                'verbose_name': 'シフトスケジュール',
                'verbose_name_plural': 'シフトスケジュール',
                'unique_together': {('employee', 'schedule_date')},
            },
        ),
        migrations.CreateModel(
            name='trn_daily_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Attendance Date')),
                ('scheduled_start', models.TimeField(verbose_name='Scheduled Start')),
                ('scheduled_end', models.TimeField(verbose_name='Scheduled End')),
                ('attendance_datetime', models.DateTimeField(verbose_name='Attendance Datetime')),
                ('closing_datetime', models.DateTimeField(verbose_name='Closing Datetime')),
                ('worked_hours', models.FloatField(verbose_name='Worked Hours')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mst_employee')),
            ],
            options={
                'ordering': ['attendance_date'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
