# Generated by Django 5.2.7 on 2025-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trn_daily_attendance',
            name='break_minutes',
            field=models.IntegerField(default=0, verbose_name='Break Minute'),
            preserve_default=False,
        ),
    ]
