# Generated by Django 5.2.7 on 2026-01-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_trn_daily_attendance_break_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trn_daily_attendance',
            name='attendance_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance Datetime'),
        ),
        migrations.AlterField(
            model_name='trn_daily_attendance',
            name='break_minutes',
            field=models.IntegerField(default=0, verbose_name='Break Minute'),
        ),
        migrations.AlterField(
            model_name='trn_daily_attendance',
            name='closing_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing Datetime'),
        ),
        migrations.AlterField(
            model_name='trn_daily_attendance',
            name='worked_hours',
            field=models.FloatField(default=0.0, verbose_name='Worked Hours'),
        ),
    ]
