# Generated by Django 5.2.7 on 2026-01-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_trn_daily_attendance_attendance_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trn_daily_attendance',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='trn_daily_attendance',
            name='scheduled_start',
        ),
    ]
