# Generated by Django 5.2.7 on 2026-01-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_remove_trn_daily_attendance_scheduled_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trn_daily_attendance',
            name='attendance_datetime',
        ),
        migrations.AlterField(
            model_name='trn_daily_attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance Date'),
        ),
    ]
