# Generated by Django 5.2.7 on 2026-01-14 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_remove_trn_daily_attendance_attendance_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trn_daily_attendance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='trn_daily_attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trn_daily_attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
