# Generated by Django 5.2.7 on 2026-01-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_alter_trn_daily_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trn_daily_attendance',
            name='attendance_date',
        ),
        migrations.AddField(
            model_name='trn_daily_attendance',
            name='attendance_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance Datetime'),
        ),
    ]
