# Generated by Django 5.2.7 on 2026-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_remove_trn_daily_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trn_clocking',
            name='clocking_type',
            field=models.CharField(choices=[('1', '出勤'), ('2', '退勤'), ('3', '休憩開始'), ('4', '休憩終了')], max_length=1, verbose_name='Clocking Type'),
        ),
    ]
