# Generated by Django 5.2.7 on 2025-12-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('schedule_app', '0002_trn_daily_attendance_break_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='対象日')),
                ('reason', models.TextField(max_length=500, verbose_name='修正理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='ステータス')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.mst_employee', verbose_name='従業員')),
                ('original_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_app.trn_daily_attendance', verbose_name='元実績データ')),
            ],
            options={
                'verbose_name': '勤怠修正申請ヘッダー',
                'verbose_name_plural': '勤怠修正申請ヘッダー',
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='TrnCorrectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(verbose_name='打刻時間（修正後）')),
                ('punch_type', models.CharField(choices=[('start', '出勤'), ('end', '退勤'), ('break_start', '休憩開始'), ('break_end', '休憩終了')], max_length=15, verbose_name='打刻内容')),
                ('sequence', models.IntegerField(default=0, verbose_name='順序')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_times', to='correction_app.trncorrectionrequest', verbose_name='修正申請')),
            ],
            options={
                'verbose_name': '勤怠修正打刻項目',
                'verbose_name_plural': '勤怠修正打刻項目',
                'ordering': ['request', 'sequence'],
            },
        ),
    ]
