# Generated by Django 5.2.7 on 2025-11-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mst_employee',
            fields=[
                ('emp_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Emp_ID')),
                ('emp_name', models.CharField(max_length=30, verbose_name='Emp_Name')),
                ('emp_age', models.IntegerField(verbose_name='Emp_Age')),
                ('emp_email', models.CharField(max_length=50, verbose_name='Emp_Email')),
                ('emp_status', models.CharField(max_length=1, verbose_name='Emp_Status')),
                ('hire_date', models.DateField(max_length=30, verbose_name='Emp_Name')),
            ],
        ),
        migrations.CreateModel(
            name='mst_shop',
            fields=[
                ('shop_id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Shop_ID')),
                ('shop_name', models.CharField(max_length=10, verbose_name='Shop_Name')),
                ('shop_addres', models.CharField(max_length=20, verbose_name='Shop_Address')),
                ('shop_tel', models.CharField(max_length=10, verbose_name='Shop_Tel')),
            ],
        ),
        migrations.CreateModel(
            name='mst_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_pass', models.CharField(max_length=50, verbose_name='Emp_Pass')),
                ('file_count', models.IntegerField(verbose_name='Fail_Count')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.mst_employee')),
            ],
        ),
        migrations.AddField(
            model_name='mst_employee',
            name='affiliated_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.mst_shop'),
        ),
        migrations.CreateModel(
            name='shift_schedule',
            fields=[
                ('schedule_date', models.DateField(primary_key=True, serialize=False, verbose_name='Schedule_Date')),
                ('start_time', models.TimeField(verbose_name='Start_Time')),
                ('End_Time', models.TimeField(verbose_name='End_Time')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.mst_employee')),
            ],
        ),
        migrations.CreateModel(
            name='trn_clocking',
            fields=[
                ('clocking_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Clocking_ID')),
                ('clocking_type', models.CharField(max_length=1, verbose_name='Clocking_Type')),
                ('clocking_datetime', models.DateTimeField(verbose_name='Clocking_DateTime')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.mst_employee')),
            ],
        ),
        migrations.CreateModel(
            name='trn_daily_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Attendance_Date')),
                ('scheduled_start', models.TimeField(verbose_name='Scheduled_Start')),
                ('scheduled_end', models.TimeField(verbose_name='Scheduled_End')),
                ('attendance_datetime', models.DateTimeField(verbose_name='Attendance_Datetime')),
                ('closing_datetime', models.DateTimeField(verbose_name='Closing_Datetime')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.mst_employee')),
            ],
        ),
    ]
