# Generated by Django 5.2.7 on 2025-11-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_mst_employee_mst_shop_mst_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift_schedule',
            options={'ordering': ['schedule_date']},
        ),
        migrations.AddField(
            model_name='mst_employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='trn_daily_attendance',
            name='worked_hours',
            field=models.FloatField(default=0.0, verbose_name=' Worked_Hours'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shift_schedule',
            unique_together={('emp_id', 'schedule_date')},
        ),
    ]
