# Generated by Django 5.2.7 on 2025-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_shift_schedule_options_mst_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_employee',
            name='hire_date',
            field=models.DateField(verbose_name='Hire_Date'),
        ),
    ]
