# Generated by Django 5.2.7 on 2025-11-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_mst_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mst_shop',
            name='shop_tel',
            field=models.CharField(max_length=11, verbose_name='Shop_Tel'),
        ),
    ]
