# Generated by Django 5.2.7 on 2025-11-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_mst_shop_shop_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift_schedule',
            old_name='End_Time',
            new_name='end_time',
        ),
    ]
